language: c++
sudo: false

matrix:
  include:
    - addons:
        apt:
          packages:
            - gcc-4.8
            - g++-4.8
    - addons:
        apt:
          packages:
            - gcc-4.9
            - g++-4.9
    - addons:
        apt:
          packages:
            - gcc-5
            - g++-5
    - addons:
        apt:
          packages:
            - gcc-6
            - g++-6

before_install:
  - cd $HOME
  # install Themis test tool
  - git clone https://github.com/rtmclay/Themis.git
  - export PATH="$PATH:$HOME/Themis/bin"
  - cd -

script:
  - g++ --version
  - pwd && ./configure && make && make install
  # run XALT test suite with Hermes
  - rtm .
