language: c++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_install:
  - cd $HOME
  # install Themis test tool
  - git clone https://github.com/rtmclay/Themis.git
  - export PATH="$PATH:$HOME/Themis/bin"
  - cd -

script:
  - g++ --version
  - pwd && ./configure && make && make install
  # run XALT test suite with Hermes
  - rtm .
